<?php

/**
 * @file
 * LocalGovDrupal demo module file.
 */

use Drupal\Core\Serialization\Yaml;

/**
 * Implements hook_modules_installed().
 *
 * Fix entity reference fields in default content.
 *
 * @see https://github.com/localgovdrupal/localgov_demo/issues/2
 */
function localgov_demo_modules_installed($modules, $is_syncing) {
  if (!$is_syncing &&
    in_array('default_content', $modules) &&
    in_array('localgov_demo', $modules)
  ) {

    // Entity reference fields to fix.
    $fix_fields = [
      'localgov_services_parent',
      'localgov_guides_parent',
      'localgov_step_parent',
    ];
    $entity_repo = \Drupal::service('entity.repository');

    // Iterate over all default node content.
    $dir = drupal_get_path('module', 'localgov_demo') . "/content/node";
    foreach (glob($dir . "/*.yml") as $filename) {

      // Load serialized content.
      $contents = file_get_contents($filename);
      $decoded = Yaml::decode($contents);

      // Get the current node id.
      $uuid_current_node = $decoded['_meta']['uuid'];
      $current_node = $entity_repo->loadEntityByUuid('node', $uuid_current_node);

      // Iterate over all field.
      foreach ($decoded['default'] as $field_name => $field) {

        // Update entity reference fields.
        if (in_array($field_name, $fix_fields)) {
          // Grab the uuid of the target node.
          $uuid_target_node = $field[0]['entity'];
          if ($uuid_target_node && $parent = $entity_repo->loadEntityByUuid('node', $uuid_target_node)) {
            if ($current_node) {
              $current_node->set($field_name, ['target_id' => $parent->id()]);
              $current_node->save();
            }
          }
        }
      }
    }

    // Regenerate all path aliases.
    // This needs to happen after entity reference fixes.
    $nids = \Drupal::entityTypeManager()->getStorage('node')->getQuery()->execute();
    $nodes = \Drupal::entityTypeManager()->getStorage('node')->loadMultiple($nids);
    foreach ($nodes as $node) {
      \Drupal::service('pathauto.generator')->updateEntityAlias($node, 'update');
    }

  }
}
