<?php

/**
 * @file
 * Install, update and uninstall functions for the localgov_demo module.
 */

use Drupal\menu_link_content\Entity\MenuLinkContent;

/**
 * Implements hook_install().
 */
function localgov_demo_install($is_syncing) {

  if (!$is_syncing) {
    // Enable area geo bundle in directory venue content type..
    $localgov_directories_venue_config = \Drupal::service('config.factory')->getEditable('field.field.node.localgov_directories_venue.localgov_location');
    $localgov_directories_venue_config->set('settings.handler_settings.target_bundles.area', 'area');
    $localgov_directories_venue_config->save();

    // Set demo front page.
    $system_site = \Drupal::configFactory()->getEditable('system.site');
    $system_site->set('page.front', '/localgov-drupal-demo');
    $system_site->save();
    drupal_flush_all_caches();

    // Disable unwanted blocks from localgov_base and localgov_scarfolk.
    $blocks_to_disable = [
      'block.block.views_block__services_block_service_list_base',
      'block.block.views_block__services_block_service_list_scarfolk',
      'block.block.localgov_home_welcome_block_base',
      'block.block.localgov_home_welcome_block_scarfolk',
    ];
    foreach ($blocks_to_disable as $block_id) {
      // Load block and set disabled.
      $services_home_block = \Drupal::configFactory()->getEditable($block_id);
      $services_home_block->set('region', 'disabled');
      $services_home_block->save();
    }
  }

  // Create main menu links.
  $main_links = [
    ['title' => 'News', 'uri' => 'internal:/news'],
    ['title' => 'Events', 'uri' => 'internal:/events'],
  ];

  foreach ($main_links as $item) {
    $menu_item = MenuLinkContent::create([
      'title' => $item['title'],
      'link' => ['uri' => $item['uri']],
      'menu_name' => 'main',
      'expanded' => FALSE,
    ]);
    $menu_item->save();
  }

  // Create footer menu links.
  $footer_links = [
    ['title' => 'Docs', 'uri' => 'https://localgovdrupal.org/', 'weight' => 1],
    ['title' => 'GitHub', 'uri' => 'https://github.com/localgovdrupal/', 'weight' => 2],
    ['title' => 'LinkedIn', 'uri' => 'https://www.linkedin.com/company/localgovdrupal/', 'weight' => 3],
    ['title' => 'Bluesky', 'uri' => 'https://bsky.app/profile/localgovdrupal.bsky.social', 'weight' => 4],
  ];

  foreach ($footer_links as $item) {
    $menu_item = MenuLinkContent::create([
      'title' => $item['title'],
      'link' => ['uri' => $item['uri']],
      'menu_name' => 'footer',
      'expanded' => FALSE,
      'weight' => isset($item['weight']) ? (int) $item['weight'] : 0,
    ]);
    $menu_item->save();
  }
}
